# action.yml
name: 'Depends DV8 analysis'
description: 'Perform analysis of architectural issues'
inputs:
  language:  # id of input
    description: 'Language of the program'
    required: true
    default: 'java'
outputs:
  result: # id of output
    description: 'Result of depends analysis'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.language }}