# action.yml
name: 'Depends DV8 analysis'
description: 'Perform analysis of architectural issues'
inputs:
  language:  # id of input
    description: 'Language of the program'
    required: true
  licenseKey:
    description: 'License key'
    required: true
  activationCode:
    description: 'Activation code'
    required: true
outputs:
  result: # id of output
    description: 'Result of depends analysis'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.language }}
    - ${{ inputs.licenseKey }}
    - ${{ inputs.activationCode }}

